#index:
#    path: /
#    controller: App\Controller\DefaultController::index

article_index:
    path: /article
    controller: App\Controller\ArticleController::index

article_by_category:
    path: '/article/category/{id}'
    controller: 'App\Controller\ArticleController::getByCategory'
    methods: ['GET']
